export const marketTypeList = () => {
	return [
		'Healthcare',
		'Government',
		'Commercial',
		'Malls',
		'Residential',
		'Retail',
		'Multi-Family Housing',
		'Low-Rise Building',
		'Mid-Rise Building',
		'High-Rise Building',
		'Industrial',
		'Warehouse',
		'Agriculture',
		'Hotels & Resorts',
		'Educational',
		'Institutional',
		'Historic Preservation',
		'Offices',
		'Parks',
		'Automotive',
		'Manufacturing',
		'Fabrication',
		'Mining',
		'Transportation',
		'Water',
		'Hydraulic',
		'Telecommunication',
		'Oil and Gas',
		'Power Plant',
		'Substation',
		'Millwork and Joinery',
	];
};
