export const softwareList = () => {
    return [
        'ArchiCAD',
        'AutoDesk 3ds Max',
        'Cabinet Vision',
        'Pytha',
        '3D Kitchen',
        'Microvellum',
        'BIM',
        'MS Powerpoint',
        'MS Word',
        'Microsoft Excel',
        'Figma',
        'Adobe XD',
        'SketchUp',
        'Autodesk Revit',
        'SolidWorks',
        'Adobe Illustrator',
        'Adobe Photoshop',
        'Adobe InDesign',
        'Autodesk Architecture',
        'V-Ray',
        'STAAD',
        'SketchUp',
        'Adobe Acrobat',
        'CATIA',
        '3DS Max',
        'Lumion',
        'Microstation',
        'Planswift',
        'Bluebeam',
        'PDS Frameworks',
        'Tekla Structures',
        'Prosteel',
    ];
};
